# Generated by Django 3.2.9 on 2021-11-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
