# Generated by Django 3.2.9 on 2021-11-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.TextField(default='{}', max_length=1024, null=True),
        ),
    ]
