# Generated by Django 3.2.9 on 2021-11-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211128_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=0, max_length=999999, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pref_channel',
            field=models.CharField(choices=[('tg', 'telegramm'), ('vk', 'vkontakte'), ('site', 'site'), ('na', 'not set')], default='na', max_length=4),
        ),
    ]
